### ISSUE TITLE
[Issue] Could not find bin/sort.dart in package arb_utils.

### ISSUE THREAD

**Issue by mirland** [Rodsevich/arb_utils#14]
After executing `flutter pub run arb_utils:sort lib/l10n/intl_en.arb` the command returns:

```
Could not find bin/sort.dart in package arb_utils.
pub finished with exit code 66
```

flutterSdkVersion= 3.0.5
package version: 0.4.0

Thanks!

**Comment by DanielArndt** [comment]
@mirland See https://github.com/Rodsevich/arb_utils/issues/6 for context, but in short the command has changed a bit:

See the revised commands at https://github.com/Rodsevich/arb_utils#bin-scripts

If you need or want to run from `flutter pub run`, then `flutter pub run arb_utils sort lib/l10n/intl_en.arb` _should_ work.

**Comment by mirland** [comment]
Daniel, thanks for the quick response. It worked perfectly.

You should release a new version with the metadata change because [pub.dev doc is old](https://pub.dev/packages/arb_utils)
<img width="877" alt="image" src="https://user-images.githubusercontent.com/8472881/199325946-9da3735d-2718-4c3b-8f16-61b969bdce0f.png">

Thanks!
