### ISSUE TITLE
Incompatible with Flutter stable `flutter_localizations` package

### ISSUE THREAD

**Issue by brian-superlist** [Rodsevich/arb_utils#19]
```
Because arb_utils >=0.6.0 depends on intl ^0.18.1 and every version of flutter_localizations from sdk depends on intl 0.18.0, arb_utils >=0.6.0 is incompatible with flutter_localizations from sdk.
```

Would you accept a PR which changes the version constraint? Is `intl` version `0.18.1` really necessary or would `0.18.0` work?

**Comment by Rodsevich** [comment]
sure! do the whole changes for a 0.6.0+1 or 0.6.1 version, whatever fits better

**Comment by Rodsevich** [comment]
By chance it's for the superlist project? If so I'd be honored to help! Reach me out on discord: Rodsevich#2576

**Comment by brian-superlist** [comment]
It is! However it's not a biggie -- we are just using it for the sorting of ARB files, which we can do in other ways. Thanks for the response :)
