### ISSUE TITLE
dart pub global activate arb_utils causes issue

### ISSUE THREAD

**Issue by AlehSabadashGmail** [Rodsevich/arb_utils#26]
I use 0.6.0 version and when I run this command in pipeline it fails with issues. 
dart pub global activate arb_utils 0.6.0

<img width="849" alt="Screenshot 2024-04-05 at 11 47 37" src="https://github.com/Rodsevich/arb_utils/assets/90776958/9f630bcd-2145-4313-9cd4-f203e3e72cf3">

I assume it is due to the new version of dart_console2 because it worked fine with dart_console2 3.0.0

<img width="467" alt="Screenshot 2024-04-05 at 11 48 34" src="https://github.com/Rodsevich/arb_utils/assets/90776958/873be171-564a-4fa2-8990-8db6a8eecf15">

Could you please fix it asap as it seems blocking using this package or suggest workaround

**Comment by micahmo** [comment]
+1 I am seeing this as well.

https://github.com/thunder-app/thunder/actions/runs/8574482382/job/23501689036#step:6:39

**Comment by Rodsevich** [comment]
this can be solved with #27
