### ISSUE TITLE
Incompatibility with Dart 3.4 Due to Removal of waitFor

### ISSUE THREAD

**Issue by nicolantean** [Rodsevich/arb_utils#28]
I'm experiencing a build error when using `arb_utils 0.8.0` and `Dart 3.4` in a Flutter project.
We are not using the library as a dependency of the project, instead, we are installing it on the CI running a step with the following command: 
`dart pub global activate arb_utils`

This is the specific error message I encountered while trying to install it:
```
Failed to build arb_utils:arb_utils:
../../../.pub-cache/hosted/pub.dev/dcli-3.4.0/lib/src/util/wait_for_ex.dart:38:17: Error: Method not found: 'waitFor'.
    value = cli.waitFor<T>(wrapped);
```
The error comes from the arb_utils dependency on an outdated version of dcli. In `dcli 4.0.0`, the waitFor method has been completely removed because it is no longer supported in Dart 3.4. As a result, projects using Dart 3.4 and arb_utils face compatibility issues. Could you please update the dependency to align with the latest dcli version? Thanks.

**Comment by Rodsevich** [comment]
Sure, @nicolantean. Just make the PR and I publish it this very night.

**Comment by thiagotognoli** [comment]
Hi @Rodsevich, #29 , please publish this pr

Thanks

**Comment by Rodsevich** [comment]
Done! Thanks a lot, guys.
