### ISSUE TITLE
Feature Request: custom sort function

### ISSUE THREAD

**Issue by 2013612** [Rodsevich/arb_utils#3]
Since I would like to sort the .arb file with case insensitive,
so I wonder if the package could take a custom sort function.
Thank you.

**Comment by defuncart** [comment]
@2013612 Yes this should be possible by updating sortARB to take an optional callback.

Feel free to open a PR and add some tests :) Or I can take a look into this at the weekend.

**Comment by Rodsevich** [comment]
Include in the PR a pubspec.yaml version bump and it's corresponding entry in the CHANGELOG.md so it'll be published ASAP

**Comment by 2013612** [comment]
Thank you for your fast replies, I would try to work on it in these days

**Comment by Rodsevich** [comment]
#4 has been merged and I've done some minor improvements, version 0.0.4 is already published in pub.dev
Thanks for your contributions, @2013612 :-D
