### ISSUE TITLE
Case insensitive flag renaming

### ISSUE THREAD

**Issue by Rodsevich** [Rodsevich/arb_utils#5]
As contributed by @2013612 in #4, the flag for case insensitive is -c, I think it's more appropiate for the job an -i flag, inspired in [RegExp modificator](http://www.regular-expressions.info/modifiers.html) and in grep command:
-i, --ignore-case
             Perform case insensitive matching.  By default, grep is case sensitive..
             
What do you think we change it now that we are on time before the users start using the feature?

**Comment by Rodsevich** [comment]
The change should be implemented in bin/sort.dart and README.md

**Comment by 2013612** [comment]
If it is a common practice of using -i for case insensitive, I think it would be better to change it now to avoid confusion.

**Comment by Rodsevich** [comment]
Uploaded the 0.1.0 version with the change implemented
